import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from db_manager import BarberDatabaseManager


class MonthlyReportGenerator:
    @staticmethod
    def generate_monthly_pdf() -> str:
        os.makedirs("generated_reports", exist_ok=True)

        month_name = datetime.utcnow().strftime("%B_%Y")
        file_path = f"generated_reports/kg_barber_monthly_report_{month_name}.pdf"

        report = BarberDatabaseManager.get_monthly_report()
        summary = report.get("summary", {})
        services = report.get("revenue_by_service", [])
        customers = report.get("top_customers", [])
        recommendations = BarberDatabaseManager.get_ai_recommendations("month")

        doc = SimpleDocTemplate(
            file_path,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "TitleStyle",
            parent=styles["Title"],
            fontSize=22,
            leading=28,
            textColor=colors.black,
            spaceAfter=14,
        )

        heading_style = ParagraphStyle(
            "HeadingStyle",
            parent=styles["Heading2"],
            fontSize=14,
            leading=18,
            textColor=colors.black,
            spaceBefore=14,
            spaceAfter=8,
        )

        body_style = ParagraphStyle(
            "BodyStyle",
            parent=styles["BodyText"],
            fontSize=10,
            leading=14,
            textColor=colors.black,
        )

        story = []

        story.append(Paragraph("KG Barber Monthly Business Report", title_style))
        story.append(Paragraph(datetime.utcnow().strftime("%B %Y"), body_style))
        story.append(Spacer(1, 16))

        story.append(Paragraph("Generated by Fade AI", body_style))
        story.append(Spacer(1, 20))

        revenue = float(summary.get("revenue") or 0)
        expenses = float(summary.get("expenses") or 0)
        profit = float(summary.get("profit") or 0)
        cash = float(summary.get("cash") or 0)
        card = float(summary.get("card") or 0)
        transactions = int(summary.get("transactions") or 0)

        kpi_data = [
            ["Revenue", f"R{revenue:,.0f}"],
            ["Expenses", f"R{expenses:,.0f}"],
            ["Profit", f"R{profit:,.0f}"],
            ["Transactions", str(transactions)],
            ["Cash", f"R{cash:,.0f}"],
            ["Card", f"R{card:,.0f}"],
        ]

        kpi_table = Table(kpi_data, colWidths=[8 * cm, 7 * cm])
        kpi_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.whitesmoke),
                    ("BOX", (0, 0), (-1, -1), 1, colors.black),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("PADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )

        story.append(Paragraph("Executive Summary", heading_style))
        story.append(kpi_table)
        story.append(Spacer(1, 18))

        story.append(Paragraph("Top Services", heading_style))

        service_rows = [["Service", "Revenue", "Transactions"]]
        for item in services[:10]:
            service_rows.append(
                [
                    item.get("service_name", "Unknown"),
                    f"R{float(item.get('revenue') or 0):,.0f}",
                    str(item.get("transactions") or 0),
                ]
            )

        if len(service_rows) == 1:
            service_rows.append(["No services recorded", "R0", "0"])

        service_table = Table(service_rows, colWidths=[7 * cm, 4 * cm, 4 * cm])
        service_table.setStyle(MonthlyReportGenerator._table_style())
        story.append(service_table)
        story.append(Spacer(1, 18))

        story.append(Paragraph("Top Customers", heading_style))

        customer_rows = [["Customer", "Revenue", "Visits"]]
        for item in customers[:10]:
            customer_rows.append(
                [
                    item.get("customer_name", "Unknown"),
                    f"R{float(item.get('revenue') or 0):,.0f}",
                    str(item.get("visits") or 0),
                ]
            )

        if len(customer_rows) == 1:
            customer_rows.append(["No customers recorded", "R0", "0"])

        customer_table = Table(customer_rows, colWidths=[7 * cm, 4 * cm, 4 * cm])
        customer_table.setStyle(MonthlyReportGenerator._table_style())
        story.append(customer_table)
        story.append(Spacer(1, 18))

        story.append(Paragraph("Payment Split", heading_style))

        total_payment = cash + card
        cash_percentage = round((cash / total_payment) * 100) if total_payment else 0
        card_percentage = round((card / total_payment) * 100) if total_payment else 0

        payment_rows = [
            ["Payment Method", "Amount", "Percentage"],
            ["Cash", f"R{cash:,.0f}", f"{cash_percentage}%"],
            ["Card", f"R{card:,.0f}", f"{card_percentage}%"],
        ]

        payment_table = Table(payment_rows, colWidths=[7 * cm, 4 * cm, 4 * cm])
        payment_table.setStyle(MonthlyReportGenerator._table_style())
        story.append(payment_table)
        story.append(Spacer(1, 18))

        story.append(Paragraph("Fade AI Commentary", heading_style))

        if recommendations:
            for rec in recommendations[:6]:
                story.append(
                    Paragraph(
                        f"<b>{rec.get('title')}</b><br/>{rec.get('message')}",
                        body_style,
                    )
                )
                story.append(Spacer(1, 8))
        else:
            story.append(
                Paragraph(
                    "No AI commentary available yet. More transactions will improve the monthly insights.",
                    body_style,
                )
            )

        story.append(Spacer(1, 20))
        story.append(Paragraph("Powered by Fade AI", body_style))

        doc.build(story)

        return file_path

    @staticmethod
    def _table_style():
        return TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.black),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
                ("BOX", (0, 0), (-1, -1), 1, colors.black),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("PADDING", (0, 0), (-1, -1), 7),
            ]
        )